### ISSUE TITLE
change to for-loop (less overhead)

### ISSUE THREAD

**Issue by cgimpl** [ngschaider/bier-in-aktion-webapp#1]
https://github.com/ngschaider/bier-in-aktion-webapp/blob/476083165a7f5106f0f33366d9b193b9e11e2deb/src/components/Content.tsx#L17

**Comment by ngschaider** [comment]
afaik, this is not possible without introducing more variables which reduces readability by a lot.
i was curious and benchmarked this. Actually, `map` performs faster in comparison to for-loops when the array contains many elements. 

I think we can neglect the overhead. Let's think about it again when the overhead gets visible.

[Benchmark](https://perf.link/#eyJpZCI6IjVwamh1em5jcjV0IiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGlucHV0ID0gWy4uLkFycmF5KDEwMDApLmtleXMoKV0iLCJ0ZXN0cyI6W3sibmFtZSI6ImZvci1sb29wIiwiY29kZSI6ImNvbnN0IG91dHB1dCA9IFtdO1xuZm9yKGxldCBpID0gMDsgaSA8IGlucHV0Lmxlbmd0aDsgaSsrKSB7XG4gIGNvbnN0IGVsID0gaW5wdXRbaV07XG4gIG91dHB1dC5wdXNoKGVsKTtcbn0iLCJydW5zIjpbMTMwMDAsMTI1MDAsMjEwMDAsMTUwMDAsMzQwMDAsMTAwMCw2MDAwLDc1MDAsMTY1MDAsMTQ1MDAsNzAwMCw2MDAwLDEwMDAsMjEwMDAsMTY1MDAsODUwMCwxNDAwMCw1MDAsMTgwMDAsNTUwMCw5MDAwLDIzNTAwLDMwMDAsMTEwMDAsNDUwMCwxMDAwMCwxMjAwMCw2MDAwLDQwMDAsNjAwMCw0MDAwLDUwMDAsMTYwMDAsMTQwMDAsNzAwMCw1NTAwLDUwMDAsMTg1MDAsMTYwMDAsODAwMCwxMDUwMCwxMjUwMCw5MDAwLDk1MDAsNzAwMCwxMDAwLDEyNTAwLDg1MDAsOTUwMCw3NTAwLDY1MDAsMTAwMDAsNTUwMCwxMDAwMCwxMTUwMCwxNjAwMCwxOTUwMCw1NTAwLDkwMDAsMTAwMCwxMDAwLDYwMDAsMTMwMDAsMTQ1MDAsMzAwMCwxNjUwMCwxNDUwMCwxNDAwMCwxMzAwMCwzMDAwLDk1MDAsMzUwMCwxMDUwMCw5MDAwLDE2MDAwLDE4MDAwLDE0NTAwLDc1MDAsMjAwMCwxMDAwLDEzNTAwLDEwMDAwLDExMDAwLDExNTAwLDEwMDAsNDAwMCw5MDAwLDk1MDAsNzAwMCw4MDAwLDU1MDAsMTUwMDAsNzUwMCwxMzAwMCwxMDAwMCw3MDAwLDE0NTAwLDEzNTAwLDcwMDAsMTAwMF0sIm9wcyI6OTc3NX0seyJuYW1lIjoiZm9yLW9mLWxvb3AiLCJjb2RlIjoiY29uc3Qgb3V0cHV0ID0gW107XG5mb3IobGV0IGVsIG9mIGlucHV0KSB7XG4gIG91dHB1dC5wdXNoKGVsKTtcbn0iLCJydW5zIjpbNDAwMCwzNTAwLDQ1MDAsMTAwMCwzNTAwLDU1MDAsNDUwMCwyMDAwLDIwMDAsNDUwMCwzMDAwLDEwMDAsMzAwMCwzNTAwLDI1MDAsMTAwMCwxMDAwLDU1MDAsMzAwMCwyNTAwLDYwMDAsNDAwMCwyNTAwLDIwMDAsMjAwMCwzMDAwLDQwMDAsMTUwMCwzNTAwLDEwMDAsMzUwMCwyNTAwLDM1MDAsNDAwMCw1NTAwLDE1MDAsNDUwMCw0NTAwLDUwMCwyMDAwLDM1MDAsMjUwMCwyMDAwLDI1MDAsMzAwMCwxMDAwLDUwMCw1MDAsMzAwMCwzMDAwLDIwMDAsNjAwMCwyMDAwLDMwMDAsNDUwMCwyNTAwLDQ1MDAsOTUwMCw0MDAwLDIwMDAsMjUwMCwyMDAwLDIwMDAsMTUwMCwyMDAwLDQ1MDAsNTAwLDM1MDAsMTAwMCwyMDAwLDMwMDAsNTAwLDE1MDAsMjAwMCw0MDAwLDMwMDAsMjUwMCwyMDAwLDUwMCwzNTAwLDQ1MDAsMzAwMCwyMDAwLDEwMDAsMzUwMCwxMDAwLDUwMDAsNDUwMCwyMDAwLDIwMDAsMzAwMCwzNTAwLDM1MDAsMTcwMDAsMzAwMCwyNTAwLDUwMCwyMDAwLDEwMDAsNTAwXSwib3BzIjoyOTMwfSx7Im5hbWUiOiIubWFwKCkiLCJjb2RlIjoiY29uc3Qgb3V0cHV0ID0gaW5wdXQubWFwKGVsID0%2BIGVsKTsiLCJydW5zIjpbNTUwMCw1NTAwLDI4NTAwLDUwMDAsNTAwMDAsMTAwMCw0NTAwLDY1MDAsMjI1MDAsMzA1MDAsNTAwMCw1MDAsNTAwLDUwMDAsNTAwMCwyMDAwLDk1MDAsMTUwMDAsMTc1MDAsNTUwMCw1MDAwLDY1MDAsMjUwMCw1NTAwLDUwMDAsNTUwMCwxOTAwMCwxMDAwLDMwMDAwLDEzNTAwLDIwMDAwLDYwMDAsMTUwMDAsMTMwMDAsNTUwMCwxMzUwMCw2NTAwLDcwMDAsNTUwMCw4NTAwLDYwMDAsMTI1MDAsMTAwMCwzMDAwLDEyMDAwLDc1MDAsMTEwMDAsODAwMCwxMDAwMCwzODAwMCwyMjAwMCw1NTAwLDQ3NTAwLDEwMDAsODUwMCw1NTAwLDU1MDAsMjUwMCwyMzAwMCw5NTAwLDU1MDAsNzUwMCw2NTAwLDcwMDAsNzAwMCwyNTUwMCw1NTAwLDE0MDAwLDQwMDAsMzEwMDAsOTAwMCw3MDAwLDUwMDAsNjUwMCwxMDAwLDE2NTAwLDM1MDAsMTM1MDAsMjAwMCwxMTAwMCw1MDAwLDUwMCw3MDAwLDE1NTAwLDMxMDAwLDg1MDAsMTYwMDAsNTAwMCwxOTAwMCw0NzUwMCwxNjUwMCw2NTAwLDEwMDAwLDE3MDAwLDEwMDAsMTEwMDAsNDAwMCwxMDUwMCw1MDAsNzUwMF0sIm9wcyI6MTA4NjV9XSwidXBkYXRlZCI6IjIwMjItMDctMDhUMTk6NTI6MTQuMTUxWiJ9)
